name: StaffSecure
version: ${project.version}
main: me.ialistannen.staffsecure.StaffSecure
depend: ["BukkitUtilities"]
authors: [I_Al_Istannen]
description: A plugin that promts users to enter a password, if their IP address changed
